### ISSUE TITLE
[BUG] `pyradiomics` fails to install on Python 3.9

### ISSUE THREAD

**Issue by goncinious** [AIM-Harvard/pyradiomics#787]
**Describe the bug**

There's no `pyradiomics` wheel for Python 3.9, therefore the package needs to be built from `sdist`. However, since build system requirements according to [PEP-518](https://peps.python.org/pep-0518/) are missing, the build fails with the following error message below (full stack trace attached).

```
(pyrad_env) # pip install pyradiomics
Collecting pyradiomics
  Downloading pyradiomics-3.0.1.tar.gz (34.5 MB)
     |████████████████████████████████| 34.5 MB 30.8 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /srv/science/test_env/pyrad_env/pyrad_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kcw59gkz/pyradiomics/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kcw59gkz/pyradiomics/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-kcw59gkz/pyradiomics/pip-egg-info
         cwd: /tmp/pip-install-kcw59gkz/pyradiomics/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kcw59gkz/pyradiomics/setup.py", line 7, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**To Reproduce**

Create Python 3.9 env and install `pyradiomics` using `pip`.
```
python -m venv pyrad_env
source pyrad_env/bin/activate
pip install pyradiomics -vvv
```

Reference issue (originally published in Poetry): https://github.com/python-poetry/poetry/issues/6484

**Expected behavior**

Could you please add Python 3.9 wheels or update `setup.py` to conform with [PEP-518](https://peps.python.org/pep-0518/)?

**Version (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Python version: 3.9
 - PyRadiomics version 3.0.1

**Additional context**
[pyradiomics_install.log](https://github.com/AIM-Harvard/pyradiomics/files/9548578/pyradiomics_install.log)

**Comment by goncinious** [comment]
Relates to https://github.com/AIM-Harvard/pyradiomics/issues/653

**Comment by andreasala98** [comment]
+1

**Comment by ludgerradke** [comment]
Pyradiomics requires Python 3.7, unfortunately the framework has not been updated to newer versions for a long time.

**Comment by dsantiago** [comment]
Yeah, we are going to 3.11 soon, maybe the framework can do a catch up to maybe 3.9 or 3.10.

**Comment by JoostJM** [comment]
I am planning to do a new release soon, supporting the newest python versions. This has not already been done so, as I've been encountering some issues with the CI integration. Especially conda is a nightmare for CI...

**Comment by dsantiago** [comment]
> I am planning to do a new release soon, supporting the newest python versions. This has not already been done so, as I've been encountering some issues with the CI integration. Especially conda is a nightmare for CI...

Good to know @JoostJM, as I am learning now radiomics and stuff for my masters, I can't do much... but in a near future, when I will be more confortable with it, I can contribute also.

**Comment by dorkylever** [comment]
Hi @JoostJM is there any update to the timeline for the newer version release?

**Comment by xyz010** [comment]
is there any updates on how to install pyradiomics on conda? After doing the following,

`conda install -c radiomics pyradiomicsI`

 am still getting the following error

`
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyradiomics

Current channels:

  - https://conda.anaconda.org/radiomics/osx-arm64
  - https://conda.anaconda.org/radiomics/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
`

**Comment by dorkylever** [comment]
Hi Joost and Ludger, 

Has there been any updates to the framework to support newer python versions? 

I'm starting to run into a lot of issues that I believe is due to the python version. 

1) Later ubuntu versions (e.g. Ubuntu 20.0.4 LTS) now have python 3.8 or later installed by default. This means that you have to add the deadsnakes ppa repository and sometimes I have issues get this to work on some systems. 

2).  Anaconda / Conda envs are installing pip v22.3.1 by default (even when python 3.17.16 is specified). This causes setup.py runs in my IDE to break (saying the install requires  >= python 3.8). That or the setuptools version is too high.

**Comment by dorkylever** [comment]
Thank you so much for updating the underlying python dependencies!!
